implement
tcet-opensource/tcet-linux-qogir-theme pull request #8
Opened 2023-10-01 16:58 UTC by divszz

## Title : Implementation of Github action

## Issue no : 

## Description
Implemented GitHub action to tcet-linux-qogir-theme repository

## Screenshots (if applicable)
N/A

## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

2023-10-01 19:16 UTC, 0xAtharv requested changes
File structure should be `.github/workflows/release.yml`

2023-10-01 19:17 UTC, 0xAtharv requested changes

2023-10-01 19:17 UTC, 0xAtharv commented on release.yml
> +       - name: Release Tar File
extra space in line 42

2023-10-02 13:44 UTC, harshau007 approved these changes
LGTM!!!!

2023-10-02 14:13 UTC, Akash6222 approved these changes
GTG

2023-10-02 14:14 UTC, Akash6222 approved these changes
solved

2023-10-02 14:14 UTC, merged